### ISSUE TITLE
Allow switch between several placeholder examples along with alternatives in descriptions

### ISSUE THREAD

**Issue by EmilySeville7cfg** [command-line-interface-pages/syntax#21]
Given this code:

```md
- Test if a specific ([f]ile/[d]irectory) exists:

`[ {string operator: -f, -d} {/?file some: ~/.bashrc|/?directory input: images} ]`
```

It should be possible to display example just for `-f` and for `-d`:

```md
- Test if a specific [f]ile exists:

`[ -f {/?file some: ~/.bashrc} ]`
```

and

```md
- Test if a specific [d]irectory exists:

`[ -d {/?directory some: ~/.bashrc} ]`
```

via smth like this `clip-view --example-alternative 1 [`. All examples are shown without `--example-alternative` option.

## Restrictions

- All placeholders must have the same number of examples.

**Comment by EmilySeville7cfg** [comment]
@kbdharun, what do u think about such idea and syntax?

**Comment by kbdharun** [comment]
> @kbdharun, what do u think about such idea and syntax?

I guess it is fine

**Comment by EmilySeville7cfg** [comment]
Syntax is slightly different than mentioned above. Please review it in my PR.
